### ISSUE TITLE
Final sensor configuration?

### ISSUE THREAD

**Issue by innrwrld** [MichelJourdain/WeatherflowTempest#1]
To where is this code going when you mention it in the final step? “Copy the code in WeatherflowTempest.yaml file.“

I’ve managed to load all the images & such from the repo into their respective directories, added my Tempest sensors to their own dashboard, but presumably just need this final configuration to apply the addon modules to the sensor datasets.  

Thanks.

**Comment by MichelJourdain** [comment]
Here is an example of a simple dashboard with instructions that works. 

https://github.com/MichelJourdain/ExempleDashboard/blob/main/README.md

**Comment by MichelJourdain** [comment]
Did you succeed? For more information you can consult this. 

https://github.com/MichelJourdain/ExempleDashboard/issues/1

**Comment by innrwrld** [comment]
Testing this out.  Thanks so much for the additional write-up.
